"""empty message

Revision ID: 1004178b8bda
Revises: f8aaf96fbc32
Create Date: 2019-05-28 09:10:06.646864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1004178b8bda'
down_revision = 'f8aaf96fbc32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('performnace', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('match')
    op.drop_table('view_replies')
    op.drop_table('manager_views')
    op.drop_table('scout_views')
    op.drop_table('view')
    op.drop_table('reply')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('reply_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('creator', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='reply_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('view',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('view_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('image_name', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='view_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('scout_views',
    sa.Column('scout_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('view_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scout_id'], ['scout.id'], name='scout_views_scout_id_fkey'),
    sa.ForeignKeyConstraint(['view_id'], ['view.id'], name='scout_views_view_id_fkey')
    )
    op.create_table('manager_views',
    sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('view_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['manager.id'], name='manager_views_manager_id_fkey'),
    sa.ForeignKeyConstraint(['view_id'], ['view.id'], name='manager_views_view_id_fkey')
    )
    op.create_table('view_replies',
    sa.Column('view_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reply_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reply_id'], ['reply.id'], name='view_replies_reply_id_fkey'),
    sa.ForeignKeyConstraint(['view_id'], ['view.id'], name='view_replies_view_id_fkey')
    )
    op.create_table('match',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('league', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('competition', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('home', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('away', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('home_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('away_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('done', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('stadium', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='match_pkey')
    )
    op.drop_table('performance')
    # ### end Alembic commands ###
