"""empty message

Revision ID: 1a40293f08a7
Revises: 5e48d7f91186
Create Date: 2019-06-01 21:11:42.791305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a40293f08a7'
down_revision = '5e48d7f91186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager_messages',
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['manager.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], )
    )
    op.create_table('scout_messages',
    sa.Column('scout_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['scout_id'], ['scout.id'], )
    )
    op.add_column('message', sa.Column('tag', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'tag')
    op.drop_table('scout_messages')
    op.drop_table('manager_messages')
    # ### end Alembic commands ###
