"""empty message

Revision ID: 1df6e88b954c
Revises: 1a40293f08a7
Create Date: 2019-06-10 09:25:41.256266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1df6e88b954c'
down_revision = '1a40293f08a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scout', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint('scout_username_key', 'scout', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('scout_username_key', 'scout', ['username'])
    op.alter_column('scout', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
