"""empty message

Revision ID: 41b026bbd264
Revises: 25c5d1257122
Create Date: 2019-05-17 13:56:50.251298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41b026bbd264'
down_revision = '25c5d1257122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_manager',
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['manager.id'], )
    )
    op.create_table('club_players',
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], )
    )
    op.add_column('club', sa.Column('logo_name', sa.String(length=200), nullable=True))
    op.drop_column('club', 'image_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club', sa.Column('image_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('club', 'logo_name')
    op.drop_table('club_players')
    op.drop_table('club_manager')
    # ### end Alembic commands ###
