"""empty message

Revision ID: 4f6d45564993
Revises: 809d9baf9cbb
Create Date: 2019-05-22 01:38:27.825318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6d45564993'
down_revision = '809d9baf9cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'points')
    # ### end Alembic commands ###
