"""empty message

Revision ID: 514be8f0f452
Revises: ba3b7acfd86c
Create Date: 2019-05-28 17:18:38.418090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514be8f0f452'
down_revision = 'ba3b7acfd86c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('shots_for', sa.Integer(), nullable=True),
    sa.Column('shots_for_ontarget', sa.Integer(), nullable=True),
    sa.Column('goals_for', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('crosses', sa.Integer(), nullable=True),
    sa.Column('crosses_successful', sa.Integer(), nullable=True),
    sa.Column('intercseptios', sa.Integer(), nullable=True),
    sa.Column('clearances', sa.Integer(), nullable=True),
    sa.Column('tackles', sa.Integer(), nullable=True),
    sa.Column('fouls', sa.Integer(), nullable=True),
    sa.Column('shots_againts', sa.Integer(), nullable=True),
    sa.Column('shots_blocked', sa.Integer(), nullable=True),
    sa.Column('goals_against', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_stats',
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('stats_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['stats_id'], ['stats.id'], )
    )
    op.add_column('club', sa.Column('ave_rating', sa.Float(), nullable=True))
    op.add_column('club', sa.Column('away_rating', sa.Float(), nullable=True))
    op.add_column('club', sa.Column('home_rating', sa.Float(), nullable=True))
    op.drop_column('player', 'red_cards')
    op.drop_column('player', 'goals')
    op.drop_column('player', 'yellow_cards')
    op.drop_column('player', 'assists')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('assists', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('yellow_cards', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('goals', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('red_cards', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('club', 'home_rating')
    op.drop_column('club', 'away_rating')
    op.drop_column('club', 'ave_rating')
    op.drop_table('player_stats')
    op.drop_table('stats')
    # ### end Alembic commands ###
