"""empty message

Revision ID: 5e48d7f91186
Revises: f90c116a0bd0
Create Date: 2019-06-01 18:34:10.761751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e48d7f91186'
down_revision = 'f90c116a0bd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('receiver_id', sa.Integer(), nullable=True))
    op.add_column('message', sa.Column('receiver_status', sa.String(length=100), nullable=True))
    op.add_column('message', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.add_column('message', sa.Column('sender_status', sa.String(length=100), nullable=True))
    op.add_column('message', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_column('message', 'tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('tag', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.drop_column('message', 'timestamp')
    op.drop_column('message', 'sender_status')
    op.drop_column('message', 'sender_id')
    op.drop_column('message', 'receiver_status')
    op.drop_column('message', 'receiver_id')
    # ### end Alembic commands ###
