"""empty message

Revision ID: 68731a6cfa06
Revises: 753a2351377f
Create Date: 2019-05-29 17:39:03.919401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68731a6cfa06'
down_revision = '753a2351377f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club', sa.Column('num_matches', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('num_matches', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('week', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'week')
    op.drop_column('player', 'num_matches')
    op.drop_column('club', 'num_matches')
    # ### end Alembic commands ###
