"""empty message

Revision ID: 753a2351377f
Revises: 7a409ccf1b3d
Create Date: 2019-05-29 10:56:19.639412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753a2351377f'
down_revision = '7a409ccf1b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('curr_perf', sa.Float(), nullable=True))
    op.drop_column('player', 'points')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('player', 'curr_perf')
    # ### end Alembic commands ###
