"""empty message

Revision ID: 7a409ccf1b3d
Revises: ef9c781f529b
Create Date: 2019-05-29 04:35:19.285079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a409ccf1b3d'
down_revision = 'ef9c781f529b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('performance', 'week',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('performance', 'week',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
