"""empty message

Revision ID: 809d9baf9cbb
Revises: a51bc5723b00
Create Date: 2019-05-21 17:50:19.727423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '809d9baf9cbb'
down_revision = 'a51bc5723b00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nonleague_match')
    op.add_column('player', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('player', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('player', sa.Column('photo_name', sa.String(length=400), nullable=False))
    op.alter_column('player', 'date_of_birth',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint('player_image_name_key', 'player', type_='unique')
    op.create_unique_constraint(None, 'player', ['photo_name'])
    op.drop_column('player', 'image_name')
    op.drop_column('player', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('image_name', sa.VARCHAR(length=400), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'player', type_='unique')
    op.create_unique_constraint('player_image_name_key', 'player', ['image_name'])
    op.alter_column('player', 'date_of_birth',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('player', 'photo_name')
    op.drop_column('player', 'last_name')
    op.drop_column('player', 'first_name')
    op.create_table('nonleague_match',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('league', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('competition', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('home', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('away', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('home_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('away_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('done', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('stadium', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='nonleague_match_pkey')
    )
    # ### end Alembic commands ###
