"""empty message

Revision ID: 89ed93ac40ea
Revises: 62ec08f5922f
Create Date: 2019-05-30 00:00:53.293838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89ed93ac40ea'
down_revision = '62ec08f5922f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manager', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('manager', sa.Column('last_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manager', 'last_name')
    op.drop_column('manager', 'first_name')
    # ### end Alembic commands ###
