"""empty message

Revision ID: a51bc5723b00
Revises: 41b026bbd264
Create Date: 2019-05-20 14:51:41.945901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a51bc5723b00'
down_revision = '41b026bbd264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manager', 'league')
    op.drop_column('manager', 'club')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manager', sa.Column('club', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('manager', sa.Column('league', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
