"""empty message

Revision ID: ba3b7acfd86c
Revises: 1004178b8bda
Create Date: 2019-05-28 09:12:57.797493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba3b7acfd86c'
down_revision = '1004178b8bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance', sa.Column('performance', sa.Float(), nullable=True))
    op.drop_column('performance', 'performnace')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance', sa.Column('performnace', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('performance', 'performance')
    # ### end Alembic commands ###
