"""empty message

Revision ID: e3ac43e43e02
Revises: f46c4115e75a
Create Date: 2019-05-29 03:27:24.974772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ac43e43e02'
down_revision = 'f46c4115e75a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('shots_against', sa.Integer(), nullable=True))
    op.drop_column('stats', 'shots_againts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('shots_againts', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('stats', 'shots_against')
    # ### end Alembic commands ###
