"""empty message

Revision ID: ef9c781f529b
Revises: e3ac43e43e02
Create Date: 2019-05-29 03:48:53.937333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9c781f529b'
down_revision = 'e3ac43e43e02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('interceptions', sa.Integer(), nullable=True))
    op.drop_column('stats', 'intercseptios')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('intercseptios', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('stats', 'interceptions')
    # ### end Alembic commands ###
