"""empty message

Revision ID: f46c4115e75a
Revises: 514be8f0f452
Create Date: 2019-05-29 01:45:23.848200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46c4115e75a'
down_revision = '514be8f0f452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_performance',
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('performance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['performance_id'], ['performance.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_performance')
    # ### end Alembic commands ###
