"""empty message

Revision ID: f90c116a0bd0
Revises: d6c21129574e
Create Date: 2019-06-01 17:09:48.624978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f90c116a0bd0'
down_revision = 'd6c21129574e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('tag', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('scout', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('scout', sa.Column('last_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scout', 'last_name')
    op.drop_column('scout', 'first_name')
    op.drop_table('message')
    # ### end Alembic commands ###
